name: REVEUR FASHION
favicon: null
layout_spectrum: 0.49521
typography_spectrum: 0.4795
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#26272c'
    - '#bcd6f2'
    - '#fefcfd'
    - '#69665d'
    - '#f3ab82'
  brandStrength: 0.7158417394384742
  lightness: 0.5100153915118426
  saturation: 0.6080418217461556
  rhythmicContrast: 0.7150790805462748
purpose: []
